# Generated by Django 4.1.1 on 2022-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('modalidad', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=40)),
                ('ciudad', models.CharField(max_length=40)),
                ('codigopostal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Traslados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
